language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pytest pytest-mock pytest-cov coveralls
  - pip install -r dev-requirements.txt
  - pip install -e .
script:
  - pytest --cov-config .coveragerc --cov=labgrid
after_success:
  - coveralls
