language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pytest pytest-mock pytest-cov coveralls
  - pip install -e .
script:
  - pytest -p no:labgrid --cov
after_success:
  - coveralls
